username=root
password=zdy15994357864
url=jdbc\:mysql\://localhost\:3306/active_v2?zeroDateTimeBehavior\=convertToNull
name=jdbc/Active_v2
auth=Container
type=javax.sql.DataSource
maxActive=50
maxIdle=30
maxWait=10000
driverClassName=com.mysql.jdbc.Driver
